# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aerial Maneuvers
email: cbullock@pivotal.io
description: >
  Strategies, stories from the trenches, and helpful tips to assist
  Concourse users on their flight to the perfect Concourse CI / CD strategy!
baseurl: "/aerial-maneuvers" # the subpath of your site, e.g. /blog
url: "http://pivotal-topher-bullock.github.io"
twitter_username: topherbullock
github_username:  pivotal-topher-bullock

# Build settings
markdown: kramdown
